# Generated by Django 2.2.2 on 2019-06-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_de_nacimiento',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
