# Generated by Django 2.2.2 on 2019-06-15 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0002_auto_20190614_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_de_nacimiento',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
