# Generated by Django 2.2.2 on 2019-06-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=250)),
                ('megas', models.CharField(choices=[('1M', '125'), ('2M', '175'), ('3M', '250'), ('4M', '310')], default='1M', max_length=2)),
            ],
        ),
    ]
